import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { redirect, notFound } from "next/navigation";
import { getUserBrandRole, safeJson } from "@/lib/utils";
import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  ArrowLeft, Target, Users, Lightbulb, BarChart2, DollarSign,
  CheckSquare, TrendingUp, Search, ExternalLink, Trophy, AlertTriangle,
  Zap, Globe, BarChart,
} from "lucide-react";
import DownloadPdfButton from "./DownloadPdfButton";

export default async function StrategyPage({ params }: { params: Promise<{ brandId: string }> }) {
  const { brandId } = await params;
  const session = await auth();
  if (!session?.user?.id) redirect("/login");

  const role = await getUserBrandRole(session.user.id, brandId);
  if (!role) notFound();

  const strategies = await prisma.marketingStrategy.findMany({
    where: { brandId },
    orderBy: { createdAt: "desc" },
    include: { user: { select: { name: true } } },
  });

  const brand = await prisma.brand.findUnique({
    where: { id: brandId },
    select: { name: true },
  });

  if (strategies.length === 0) {
    return (
      <div className="p-8 max-w-4xl mx-auto text-center">
        <p className="text-gray-500 mt-20">No strategy yet. Go back and generate one.</p>
        <Link href={`/brands/${brandId}`} className="inline-block mt-4">
          <Badge variant="outline">← Back to Brand</Badge>
        </Link>
      </div>
    );
  }

  const strategy = strategies[0];

  const targetAudience = safeJson(strategy.targetAudience) as {
    primary?: string; secondary?: string; keyInsights?: string[];
  } | null;
  const valueProps = safeJson(strategy.valuePropositions) as string[] | null;
  const pillars = safeJson(strategy.contentPillars) as Array<{
    name: string; description: string; percentage: number;
  }> | null;
  const channelMix = safeJson(strategy.channelMix) as Record<string, {
    focus: string; contentType: string; frequency: string; campaignType?: string; budget?: string;
  }> | null;
  const kpis = safeJson(strategy.kpis) as string[] | null;
  const budgetSplit = safeJson(strategy.budgetSplit) as {
    organic?: number; paidSocial?: number; paidSearch?: number;
  } | null;

  // Parse competitive intelligence from rawContent
  const rawData = safeJson(strategy.rawContent) as Record<string, unknown> | null;
  const ci = rawData?.competitiveIntelligence as CompetitiveIntelligence | null;
  const searchMethod = rawData?._searchMethod as string | null;

  return (
    <div className="p-8 max-w-6xl mx-auto">
      {/* Header */}
      <div className="mb-8">
        <Link href={`/brands/${brandId}`} className="inline-flex items-center gap-1.5 text-sm text-gray-500 hover:text-gray-700 mb-4">
          <ArrowLeft className="h-4 w-4" />
          Back to {brand?.name}
        </Link>
        <div className="flex items-start justify-between gap-4 flex-wrap">
          <div className="flex items-center gap-3 flex-wrap">
            <h1 className="text-2xl font-bold text-gray-900">{strategy.title}</h1>
            {strategy.isActive && <Badge variant="success">Active</Badge>}
            <Badge variant="outline">v{strategy.version}</Badge>
            {searchMethod && (
              <Badge variant={searchMethod === "web_search" ? "default" : "secondary"} className="gap-1">
                {searchMethod === "web_search" ? (
                  <><Globe className="h-3 w-3" /> Web Search Enriched</>
                ) : (
                  <><Search className="h-3 w-3" /> AI Knowledge</>
                )}
              </Badge>
            )}
          </div>
          <DownloadPdfButton brandId={brandId} />
        </div>
        <p className="text-gray-400 text-sm mt-1">
          Generated by {strategy.user?.name ?? "AI"} · {new Date(strategy.createdAt).toLocaleDateString()}
        </p>
      </div>

      {/* ── Competitive Intelligence (highlighted section) ─────────────────── */}
      {ci && (
        <div className="mb-8 bg-gradient-to-br from-slate-900 to-indigo-950 rounded-2xl p-6 text-white">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 bg-indigo-500/20 rounded-xl flex items-center justify-center border border-indigo-400/30">
              <TrendingUp className="h-5 w-5 text-indigo-300" />
            </div>
            <div>
              <h2 className="text-lg font-bold text-white">Competitive Intelligence</h2>
              <p className="text-indigo-300 text-xs">
                {searchMethod === "web_search"
                  ? `Real-time web research · ${ci.sources?.length ?? 0} sources analysed`
                  : "Based on AI training knowledge"}
              </p>
            </div>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
            {/* Top Competitors */}
            {ci.topCompetitors && ci.topCompetitors.length > 0 && (
              <div className="lg:col-span-2">
                <p className="text-xs font-semibold text-indigo-300 uppercase tracking-wider mb-3">
                  Top Competitors
                </p>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
                  {ci.topCompetitors.map((comp, i) => (
                    <div key={i} className="bg-white/5 border border-white/10 rounded-xl p-4">
                      <div className="flex items-start justify-between mb-2">
                        <p className="font-semibold text-white text-sm">{comp.name}</p>
                        {comp.estimatedReach && (
                          <span className="text-[10px] bg-indigo-500/30 text-indigo-200 px-2 py-0.5 rounded-full whitespace-nowrap ml-2">
                            {comp.estimatedReach}
                          </span>
                        )}
                      </div>
                      <p className="text-xs text-slate-300 mb-2">{comp.marketingApproach}</p>
                      {comp.keyTactics && comp.keyTactics.length > 0 && (
                        <div className="flex flex-wrap gap-1">
                          {comp.keyTactics.map((t, j) => (
                            <span key={j} className="text-[10px] bg-white/10 text-slate-300 px-1.5 py-0.5 rounded">
                              {t}
                            </span>
                          ))}
                        </div>
                      )}
                      {comp.relevantData && (
                        <p className="text-[10px] text-indigo-300 mt-2 font-mono border-t border-white/10 pt-2">
                          📊 {comp.relevantData}
                        </p>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Success Cases */}
            {ci.successCases && ci.successCases.length > 0 && (
              <div>
                <p className="text-xs font-semibold text-indigo-300 uppercase tracking-wider mb-3 flex items-center gap-1.5">
                  <Trophy className="h-3.5 w-3.5" />
                  Success Cases
                </p>
                <div className="space-y-3">
                  {ci.successCases.map((sc, i) => (
                    <div key={i} className="bg-white/5 border border-white/10 rounded-xl p-3">
                      <div className="flex items-center gap-2 mb-1">
                        <span className="text-sm font-medium text-white">{sc.brand}</span>
                        {sc.campaign && (
                          <span className="text-[10px] text-slate-400">· {sc.campaign}</span>
                        )}
                      </div>
                      <p className="text-xs text-slate-300 mb-1.5">{sc.tactic}</p>
                      {sc.data && (
                        <div className="flex items-center gap-1.5 bg-emerald-500/15 border border-emerald-500/20 rounded-lg px-2.5 py-1.5">
                          <BarChart className="h-3 w-3 text-emerald-400 flex-shrink-0" />
                          <span className="text-xs text-emerald-300 font-medium">{sc.data}</span>
                        </div>
                      )}
                      {!sc.data && sc.result && (
                        <p className="text-xs text-emerald-400">✓ {sc.result}</p>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Industry Benchmarks */}
            {ci.industryBenchmarks && ci.industryBenchmarks.length > 0 && (
              <div>
                <p className="text-xs font-semibold text-indigo-300 uppercase tracking-wider mb-3 flex items-center gap-1.5">
                  <BarChart2 className="h-3.5 w-3.5" />
                  Industry Benchmarks
                </p>
                <div className="space-y-2">
                  {ci.industryBenchmarks.map((b, i) => (
                    <div key={i} className="flex items-start gap-2 bg-white/5 rounded-lg px-3 py-2">
                      <span className="text-amber-400 mt-0.5 flex-shrink-0 text-sm">◆</span>
                      <p className="text-xs text-slate-200">{b}</p>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Market Gaps */}
            {ci.marketGaps && ci.marketGaps.length > 0 && (
              <div>
                <p className="text-xs font-semibold text-indigo-300 uppercase tracking-wider mb-3 flex items-center gap-1.5">
                  <Zap className="h-3.5 w-3.5" />
                  Market Gaps (Opportunities)
                </p>
                <div className="space-y-2">
                  {ci.marketGaps.map((gap, i) => (
                    <div key={i} className="flex items-start gap-2 bg-yellow-500/10 border border-yellow-500/20 rounded-lg px-3 py-2">
                      <AlertTriangle className="h-3.5 w-3.5 text-yellow-400 flex-shrink-0 mt-0.5" />
                      <p className="text-xs text-yellow-200">{gap}</p>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Differentiation */}
            {ci.differentiationOpportunity && (
              <div className="lg:col-span-2 bg-indigo-500/15 border border-indigo-500/30 rounded-xl p-4">
                <p className="text-xs font-semibold text-indigo-300 uppercase tracking-wider mb-2 flex items-center gap-1.5">
                  <Target className="h-3.5 w-3.5" />
                  How to Stand Out vs Competitors
                </p>
                <p className="text-sm text-slate-200">{ci.differentiationOpportunity}</p>
              </div>
            )}
          </div>

          {/* Sources */}
          {ci.sources && ci.sources.length > 0 && (
            <div className="mt-5 pt-4 border-t border-white/10">
              <p className="text-xs text-slate-500 mb-2">Research sources:</p>
              <div className="flex flex-wrap gap-2">
                {ci.sources.slice(0, 6).map((src, i) => (
                  <a
                    key={i}
                    href={src.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex items-center gap-1 text-[10px] text-slate-400 hover:text-indigo-300 bg-white/5 px-2 py-1 rounded transition-colors"
                  >
                    <ExternalLink className="h-2.5 w-2.5" />
                    {src.title.slice(0, 40)}{src.title.length > 40 ? "..." : ""}
                  </a>
                ))}
              </div>
            </div>
          )}
        </div>
      )}

      {/* ── Strategy content grid ──────────────────────────────────────────── */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Positioning */}
        {strategy.positioning && (
          <Card className="lg:col-span-2">
            <CardHeader className="pb-3">
              <CardTitle className="text-base flex items-center gap-2">
                <Target className="h-4 w-4 text-indigo-600" />
                Positioning Statement
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-gray-700 leading-relaxed">{strategy.positioning}</p>
            </CardContent>
          </Card>
        )}

        {/* Target Audience */}
        {targetAudience && (
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-base flex items-center gap-2">
                <Users className="h-4 w-4 text-purple-600" />
                Target Audience
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              {targetAudience.primary && (
                <div>
                  <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1">Primary</p>
                  <p className="text-sm text-gray-700">{targetAudience.primary}</p>
                </div>
              )}
              {targetAudience.secondary && (
                <div>
                  <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1">Secondary</p>
                  <p className="text-sm text-gray-700">{targetAudience.secondary}</p>
                </div>
              )}
              {targetAudience.keyInsights && targetAudience.keyInsights.length > 0 && (
                <div>
                  <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2">Key Insights</p>
                  <ul className="space-y-1">
                    {targetAudience.keyInsights.map((insight, i) => (
                      <li key={i} className="flex items-start gap-2 text-sm text-gray-600">
                        <span className="w-1.5 h-1.5 rounded-full bg-purple-400 mt-1.5 flex-shrink-0" />
                        {insight}
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </CardContent>
          </Card>
        )}

        {/* Value Propositions */}
        {valueProps && valueProps.length > 0 && (
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-base flex items-center gap-2">
                <Lightbulb className="h-4 w-4 text-amber-600" />
                Value Propositions
              </CardTitle>
            </CardHeader>
            <CardContent>
              <ul className="space-y-2">
                {valueProps.map((vp, i) => (
                  <li key={i} className="flex items-start gap-2 text-sm text-gray-700">
                    <span className="text-amber-500 font-bold flex-shrink-0">{i + 1}.</span>
                    {vp}
                  </li>
                ))}
              </ul>
            </CardContent>
          </Card>
        )}

        {/* Content Pillars */}
        {pillars && pillars.length > 0 && (
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-base flex items-center gap-2">
                <BarChart2 className="h-4 w-4 text-indigo-600" />
                Content Pillars
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              {pillars.map((pillar, i) => (
                <div key={i}>
                  <div className="flex items-center justify-between mb-1">
                    <p className="text-sm font-medium text-gray-900">{pillar.name}</p>
                    <span className="text-xs text-gray-500 font-mono">{pillar.percentage}%</span>
                  </div>
                  <div className="h-1.5 bg-gray-100 rounded-full overflow-hidden mb-1">
                    <div
                      className="h-full bg-gradient-to-r from-indigo-500 to-purple-500 rounded-full"
                      style={{ width: `${pillar.percentage}%` }}
                    />
                  </div>
                  {pillar.description && (
                    <p className="text-xs text-gray-500">{pillar.description}</p>
                  )}
                </div>
              ))}
            </CardContent>
          </Card>
        )}

        {/* Channel Mix */}
        {channelMix && (
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-base flex items-center gap-2">
                <Globe className="h-4 w-4 text-blue-600" />
                Channel Mix
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              {Object.entries(channelMix).map(([channel, details]) => (
                <div key={channel} className="border border-gray-100 rounded-lg p-3">
                  <p className="text-sm font-semibold text-gray-900 mb-2 capitalize">
                    {channel === "googleAds" ? "Google Ads" : channel === "facebook" ? "Facebook" : channel === "instagram" ? "Instagram" : channel}
                  </p>
                  {details.focus && <p className="text-xs text-gray-600 mb-1"><span className="font-medium">Focus:</span> {details.focus}</p>}
                  {details.contentType && <p className="text-xs text-gray-600 mb-1"><span className="font-medium">Content:</span> {details.contentType}</p>}
                  {details.frequency && <p className="text-xs text-gray-600"><span className="font-medium">Frequency:</span> {details.frequency}</p>}
                </div>
              ))}
            </CardContent>
          </Card>
        )}

        {/* Budget Split */}
        {budgetSplit && (
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-base flex items-center gap-2">
                <DollarSign className="h-4 w-4 text-emerald-600" />
                Budget Split
              </CardTitle>
            </CardHeader>
            <CardContent>
              {[
                { label: "Organic Content", value: budgetSplit.organic ?? 0, color: "bg-indigo-500" },
                { label: "Paid Social", value: budgetSplit.paidSocial ?? 0, color: "bg-pink-500" },
                { label: "Paid Search", value: budgetSplit.paidSearch ?? 0, color: "bg-amber-500" },
              ].map(({ label, value, color }) => (
                <div key={label} className="mb-3">
                  <div className="flex items-center justify-between mb-1">
                    <p className="text-sm text-gray-700">{label}</p>
                    <span className="text-sm font-semibold text-gray-900">{value}%</span>
                  </div>
                  <div className="h-2 bg-gray-100 rounded-full overflow-hidden">
                    <div className={`h-full ${color} rounded-full`} style={{ width: `${value}%` }} />
                  </div>
                </div>
              ))}
            </CardContent>
          </Card>
        )}

        {/* KPIs */}
        {kpis && kpis.length > 0 && (
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-base flex items-center gap-2">
                <CheckSquare className="h-4 w-4 text-emerald-600" />
                Key KPIs
              </CardTitle>
            </CardHeader>
            <CardContent>
              <ul className="space-y-1.5">
                {kpis.map((kpi, i) => (
                  <li key={i} className="flex items-center gap-2 text-sm text-gray-700">
                    <CheckSquare className="h-3.5 w-3.5 text-emerald-500 flex-shrink-0" />
                    {kpi}
                  </li>
                ))}
              </ul>
            </CardContent>
          </Card>
        )}
      </div>

      {/* Previous strategies */}
      {strategies.length > 1 && (
        <div className="mt-8">
          <h2 className="font-semibold text-gray-700 mb-3">Previous Versions</h2>
          <div className="space-y-2">
            {strategies.slice(1).map((s) => (
              <div key={s.id} className="flex items-center gap-3 p-3 rounded-lg bg-white border border-gray-200">
                <Badge variant="secondary">v{s.version}</Badge>
                <span className="text-sm text-gray-700">{s.title}</span>
                <span className="text-xs text-gray-400 ml-auto">{new Date(s.createdAt).toLocaleDateString()}</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

// ─── Types ────────────────────────────────────────────────────────────────────

interface CompetitiveIntelligence {
  topCompetitors?: Array<{
    name: string;
    marketingApproach: string;
    keyTactics?: string[];
    estimatedReach?: string;
    relevantData?: string;
  }>;
  successCases?: Array<{
    brand: string;
    campaign?: string;
    tactic: string;
    result: string;
    data?: string;
  }>;
  industryBenchmarks?: string[];
  marketGaps?: string[];
  differentiationOpportunity?: string;
  searchMethod?: string;
  sources?: Array<{ title: string; url: string }>;
}
